name: 'NX Migration Bot'
description: 'This Action checks your current NX version, migrates the project in a new branch and opens a PR.'
author: 'Timon Masberg'
inputs:
  repoToken:
    required: true
    description: Repository secret
  prTitle:
    required: false
    description: 'Title of the PR where $VERSION is the new version of NX.'
    default: 'Migrate NX to $VERSION'
  commitMessage:
    required: false
    description: 'Commit Message where $VERSION is the new version of NX.'
    default: 'migrates NX to $VERSION'
  includeMigrationsFile:
    required: false
    description: 'If false, the migrations.json file will be deleted after running the migrations. It is considered best-practice to check-in the migrations.json.'
    default: 'true'
outputs:
  prId:
    description: 'Issue ID of the created PR'


runs:
  using: 'node16'
  main: 'dist/index.js'
