import {exec} from '@actions/exec'

export async function prepareGit(
  origin: string,
  branchName: string
): Promise<void> {
  await exec(`git checkout -b ${branchName}`)
  await exec(
    `git config --local user.email "github-actions[bot]@users.noreply.github.com"`
  )
  await exec(`git config --local user.name "github-actions[bot]"`)
  await exec(`git remote set-url origin ${origin}`)
}

export async function pushChangesToRemote(branchName: string): Promise<void> {
  await exec(`git push --force-with-lease -u origin ${branchName}`)
}

export function makePRBody(publishedAt: string, releaseUrl: string): string {
  return `This PR migrates the project to the latest stable version of NX.  

**Published:**  
${publishedAt}  

**Release URL:**  
${releaseUrl}  

<sub>This PR has been automatically generated by the [NX Migration Github Action](https://github.com/timonmasberg/nx-migration-gh-action).</sub>
`
}
