import {exec} from '@actions/exec'

export async function pushChangesToRemote(commitMessage: string, repoName: string, origin: string) {
  await exec(`git config --local user.email "github-actions[bot]@users.noreply.github.com"`)
  await exec(`git config --local user.name "github-actions[bot]"`)
  await exec(`git remote set-url origin ${origin}`)

  await exec(`git checkout -b ${repoName}`)
  await exec('git add .')
  await exec(
    `git commit -m "${commitMessage}"`
  )

  await exec(`git push --force-with-lease -u origin ${repoName}`)
}


export function makePRBody(releaseNotes: string, publishedAt: string, releaseUrl: string): string {
  return `<h2>Release Notes:</h2><br>${releaseNotes}<br><b>Published:</b> ${publishedAt}<br><b>Release URL:</b> ${releaseUrl} <br> <br> <small>This PR has been generated by the NX Migration Action (https://github.com/timonmasberg/nx-migration-gh-action)</small>`;
}
